// <auto-generated />
using System;
using Domain.Data.EntityFrameworkModels.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Domain.Migrations
{
    [DbContext(typeof(ContextWoolworths))]
    [Migration("20200511040558_Added timestamp")]
    partial class Addedtimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Data.EntityFrameworkModels.Models.Woolworths", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("CMBuyer")
                        .IsRequired()
                        .HasColumnName("cm_buyer")
                        .HasColumnType("text");

                    b.Property<LocalDate>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("date_added")
                        .HasColumnType("date")
                        .HasDefaultValueSql("current_date");

                    b.Property<LocalDate?>("FinalSubmissionDateForBrandedProducts")
                        .HasColumnName("final_submission_for_branded")
                        .HasColumnType("date");

                    b.Property<string>("HOB")
                        .IsRequired()
                        .HasColumnName("hob")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<LocalDate?>("InfoOfNewAndDeletedLines")
                        .HasColumnName("info_of_new_and_deleted_lines")
                        .HasColumnType("date");

                    b.Property<string>("MM")
                        .IsRequired()
                        .HasColumnName("mm")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<LocalDate?>("NoticeOfProbableDelisting")
                        .HasColumnName("notice_of_probable_delisting")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("ProvideAllWnasWafWpfToBuyers")
                        .HasColumnName("provide_all_wnas_waf_wpf_to_buyer")
                        .HasColumnType("date");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnName("sub_cat_name")
                        .HasColumnType("text");

                    b.Property<LocalDate?>("SubDateForFoodCoOwnBrandProducts")
                        .HasColumnName("sub_date_foodco_products")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("SuppliersEngagement")
                        .HasColumnName("suppliers_engagement")
                        .HasColumnType("date");

                    b.Property<string>("TypeOfReview")
                        .IsRequired()
                        .HasColumnName("review_type")
                        .HasColumnType("text");

                    b.Property<LocalDate>("VisualPlanogramDueToStores")
                        .HasColumnName("visual_planogram_due_to_stores")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("pk_woolworths");

                    b.ToTable("category_dev_schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
