// <auto-generated />
using System;
using Domain.Data.EntityFrameworkModels.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Domain.Migrations
{
    [DbContext(typeof(ContextWoolworths))]
    partial class ContextWoolworthsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Data.EntityFrameworkModels.Models.Woolworths", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("CMBuyer")
                        .IsRequired()
                        .HasColumnName("cm_buyer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinalSubmissionDateForBrandedProducts")
                        .HasColumnName("final_submission_for_branded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HOB")
                        .IsRequired()
                        .HasColumnName("hob")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime?>("InfoOfNewAndDeletedLines")
                        .HasColumnName("info_of_new_and_deleted_lines")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MM")
                        .IsRequired()
                        .HasColumnName("mm")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime?>("NoticeOfProbableDelisting")
                        .HasColumnName("notice_of_probable_delisting")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ProvideAllWnasWafWpfToBuyers")
                        .HasColumnName("provide_all_wnas_waf_wpf_to_buyer")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnName("sub_cat_name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubDateForFoodCoOwnBrandProducts")
                        .HasColumnName("sub_date_foodco_products")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SuppliersEngagement")
                        .HasColumnName("suppliers_engagement")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TypeOfReview")
                        .IsRequired()
                        .HasColumnName("review_type")
                        .HasColumnType("text");

                    b.Property<DateTime>("VisualPlanogramDueToStores")
                        .HasColumnName("visual_planogram_due_to_stores")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Woolworths");
                });
#pragma warning restore 612, 618
        }
    }
}
